# Project information
site_name: BOSAGORA Documentation
site_url: https://bosagora-documentation.readthedocs.io/
site_author: BOSAGORA

# Repository
repo_name: bosagora/docs-bosagora-io
repo_url: https://github.com/bosagora/docs-bosagora-io
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 BOSAGORA

# Configuration
theme:
  name: material
  custom_dir: docs/overrides

  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

  favicon: assets/favicon.ico
  logo: assets/favicon.ico

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bosagora1
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/BOSAGORA
    - icon: fontawesome/brands/medium
      link: https://medium.com/bosagora
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCjcTwkskyTmAwHpqv9Oynig
    - icon: fontawesome/brands/github
      link: https://github.com/bosagora

# Page tree
nav:
  - Home: index.md
  - New to Bosagora:
    - What is a Blockchain?: 01-what-is-a-blockchain.md
    - What is a Cryptocurrency?: 02-what-is-a-cryptocurrency.md
    - Why The Need For Bosagora?: 03-why-the-need-for-bosagora.md
    - Bosagora Platform Overview: 04-bosagora-platform-overview.md
    - Trust Contracts: 05-trust-contracts.md
    - Proof of Stake: 06-proof-of-stake.md
    - Bosagora Nodes: 07-bosagora-nodes.md
    - How to Purchase BOA: 08-how-to-purchase-boa.md
  - Learn:
    - Consensus Algorithm: 09-consensus-algorithm.md
    - DAO: 10-dao.md
    - UTXO Configuration: 11-utxo-configuration.md
    - Quorums: 12-quorums.md
    - Flash Layer: 13-flash-layer.md
  - Releases:
    - Changelog: changelog.md
  - Wallet(한국어):
    - 소개: ./ko/01-introduction.md
    - 로그인: ./ko/02-login.md
    - 상단 정보 설명: ./ko/03-top.md
    - 개요: ./ko/04-overview.md
    - 트랜잭션 내역: ./ko/05-transaction-history.md
    - BOA 전송: ./ko/06-send-boa.md
    - 검증자 생성: ./ko/07-create-validator.md
    - 언프리징: ./ko/08-unfreezing.md
    - 데이터 저장: ./ko/09-store-data.md
    - 연락처 목록: ./ko/10-contact.md
    - 설정: ./ko/11-setting.md
  - Wallet(English):
    - Introducetion: ./en/01-introduction.md
    - Login: ./en/02-login.md
    - Top: ./en/03-top.md
    - Overview: ./en/04-overview.md
    - Transactions history: ./en/05-transaction-history.md
    - Send BOA: ./en/06-send-boa.md
    - Create validator: ./en/07-create-validator.md
    - Unfreezing: ./en/08-unfreezing.md
    - Store Data: ./en/09-store-data.md
    - Contact: ./en/10-contact.md
    - Setting: ./en/11-setting.md
